<?php

/**
 * ArtisanPack UI Unified Configuration.
 *
 * This file is automatically generated by the artisanpack:scaffold-config command.
 * It contains the default settings from all installed ArtisanPack UI packages.
 * You can safely modify these values to customize your application.
 */
return [
    'icons' => [
        'sets' => [
            'artisanpack' => [
                'path' => resource_path('icons/artisanpack'),
                'prefix' => 'ap',
            ],
        ],
    ],

    /*
     * Remote-admin API knobs (V2_REFACTOR_PLAN.md §8.2, §9.6 #43).
     * `rate_limit_per_minute` is consumed by the `api` limiter
     * registered in AppServiceProvider.
     */
    'api' => [
        'rate_limit_per_minute' => (int) env('API_RATE_LIMIT_PER_MINUTE', 60),
    ],

    /*
     * Scheduled `packages:sync-versions` run that keeps `packages.version`
     * in step with the latest stable Packagist / npm release.
     */
    'packages' => [
        'version_sync_enabled' => (bool) env('PACKAGE_VERSION_SYNC_ENABLED', true),
    ],
];
